### Hello
GET http://localhost:3000/

### Listar libros
GET http://localhost:3000/libros

### Listar autores
GET http://localhost:3000/autores

### Buscar autor existente
GET http://localhost:3000/autores/1

### Buscar autor inexistente - 404
GET http://localhost:3000/autores/999

### Crear autor
POST http://localhost:3000/autores
Content-Type: application/json

{
  "nombre": "Julio Cortázar"
}

### Crear autor sin nombre - 400
POST http://localhost:3000/autores
Content-Type: application/json

{}

### Actualizar autor
PUT http://localhost:3000/autores/1
Content-Type: application/json

{
  "nombre": "J.R.R. Tolkien Actualizado"
}

### Actualizar autor inexistente - 404
PUT http://localhost:3000/autores/999
Content-Type: application/json

{
  "nombre": "Autor inexistente"
}

### Eliminar autor
DELETE http://localhost:3000/autores/2

### Eliminar autor inexistente - 404
DELETE http://localhost:3000/autores/999